version: "3.9"

services:
    runner:
        image: orderbook_monitor
        container_name: orderbook_monitor
        build: .
        volumes: 
            - .:/work
        command: python main.py
        depends_on: 
            - db
        environment:
            - POSTGRES_HOST=db

    db:
        image: postgres:13
        container_name: db
        restart: always
        ports: 
            - 5432:5432
        volumes:
            - ./data/psql_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=orderbook_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

